-- Revenue by Customer Location (Region-Wise Sales Analysis)

-- 🎯 Problem Statement:

-- “Find out the total revenue generated from each customer location based on their confirmed orders.”
-- Query to calculate total revenue generated by each customer location based on confirmed orders.

SELECT * FROM PRODUCTANALYSIS.PUBLIC.ORDERS;
SELECT * FROM PRODUCTANALYSIS.PUBLIC.USERS;

SELECT
    u.location,
    SUM(o.amount) as total_revenue
FROM
    PRODUCTANALYSIS.PUBLIC.ORDERS o
INNER JOIN
    PRODUCTANALYSIS.PUBLIC.USERS u
ON o.user_id = u.user_id
WHERE 
    o.status = 'confirmed'
GROUP BY
    u.location;
