CREATE OR REPLACE TABLE PRODUCTANALYSIS.PUBLIC.EVENTS (
  event_id INT PRIMARY KEY,
  user_id INT NOT NULL REFERENCES PRODUCTANALYSIS.PUBLIC.USERS(user_id),
  product_id INT NOT NULL REFERENCES PRODUCTANALYSIS.PUBLIC.PRODUCTS(product_id),
  event_type VARCHAR(100) NOT NULL,
  event_time TIMESTAMP
);