CREATE OR REPLACE TABLE PRODUCTANALYSIS.PUBLIC.ORDERS (
  order_id INT PRIMARY KEY,
  user_id INT NOT NULL REFERENCES PRODUCTANALYSIS.PUBLIC.USERS(user_id),
  product_id INT NOT NULL REFERENCES PRODUCTANALYSIS.PUBLIC.PRODUCTS(product_id),
  order_date DATE,
  quantity INT,
  amount DECIMAL,
  status VARCHAR(25) DEFAULT 'confirmed'
);