CREATE OR REPLACE TABLE PRODUCTANALYSIS.PUBLIC.USERS (
  user_id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  signup_date DATE NOT NULL,
  location VARCHAR(100)
);